"""add ots_filename to transactions

Revision ID: 2d64d798fb3e
Revises: c6ab46450705
Create Date: 2025-05-15 15:13:34.632157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d64d798fb3e'
down_revision = 'c6ab46450705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ots_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('ots_filename')

    # ### end Alembic commands ###
